import { MediaItem } from "@/types/media";

export const mockMedia: MediaItem[] = [
  {
    id: "1",
    slug: "alfatiha-calm-nature-4k",
    title_ar: "الفاتحة | تلاوة هادئة مع مشهد طبيعي",
    description_ar: "تلاوة روحانية بدقة عالية مع خلفية طبيعية متناسقة.",
    media_kind: "quran_video",
    category: "فيديوهات القرآن",
    reciter: "مشاري العفاسي",
    surah: "الفاتحة",
    duration_seconds: 186,
    tags: ["فاتحة", "هادئ", "طبيعة", "4K"],
    resolution: "4K",
    file_type: "mp4",
    video_url: "https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1519817914152-22f90e6c7f39?auto=format&fit=crop&w=1200&q=80",
    views_count: 11432,
    saves_count: 2411,
    created_at: "2026-04-10T12:00:00Z",
    published_at: "2026-04-10T12:00:00Z",
    is_featured: true,
    mood: "هادئ",
    aspect_ratio: "16:9",
    language_code: "ar",
  },
  {
    id: "2",
    slug: "alkahf-blue-sky-visual",
    title_ar: "سورة الكهف | خلفية سماء زرقاء سينمائية",
    description_ar: "مقطع بصري قرآني مناسب للمونتاج الإسلامي الاحترافي.",
    media_kind: "quran_video",
    category: "فيديوهات القرآن",
    reciter: "عبد الباسط",
    surah: "الكهف",
    duration_seconds: 422,
    tags: ["الكهف", "سماء", "سينمائي"],
    resolution: "1080p",
    file_type: "mp4",
    video_url: "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    views_count: 9543,
    saves_count: 1910,
    created_at: "2026-04-09T12:00:00Z",
    published_at: "2026-04-09T12:00:00Z",
    aspect_ratio: "16:9",
    language_code: "ar",
  },
  {
    id: "3",
    slug: "islamic-gold-calligraphy-loop",
    title_ar: "خلفية خط عربي ذهبي متحرك",
    description_ar: "تصميم إسلامي فاخر بخط عربي ولمسة ذهبية راقية.",
    media_kind: "islamic_design",
    category: "تصاميم إسلامية",
    duration_seconds: 78,
    tags: ["خط عربي", "ذهبي", "موشن"],
    resolution: "4K",
    file_type: "mp4",
    video_url: "https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1495195134817-aeb325a55b65?auto=format&fit=crop&w=1200&q=80",
    views_count: 7134,
    saves_count: 2104,
    created_at: "2026-04-08T12:00:00Z",
    published_at: "2026-04-08T12:00:00Z",
    is_featured: true,
    aspect_ratio: "16:9",
    language_code: "ar",
  },
  {
    id: "4",
    slug: "green-screen-islamic-frame",
    title_ar: "إطار إسلامي كروما جاهز للمونتاج",
    description_ar: "فيديو شاشة خضراء بإطار زخرفي إسلامي عالي الجودة.",
    media_kind: "chroma",
    category: "كروما",
    duration_seconds: 45,
    tags: ["كروما", "إطار", "مونتاج"],
    resolution: "1080p",
    file_type: "mp4",
    video_url: "https://storage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1490730141103-6cac27aaab94?auto=format&fit=crop&w=1200&q=80",
    views_count: 4011,
    saves_count: 1322,
    created_at: "2026-04-07T12:00:00Z",
    published_at: "2026-04-07T12:00:00Z",
    aspect_ratio: "16:9",
    language_code: "ar",
  },
  {
    id: "5",
    slug: "nature-river-quran-bed",
    title_ar: "مشهد نهر هادئ متزامن مع تلاوة",
    description_ar: "خلفية طبيعية مناسبة لتلاوات بصرية تأملية.",
    media_kind: "nature_scene",
    category: "مشاهد طبيعية",
    duration_seconds: 200,
    tags: ["نهر", "طبيعة", "تأمل"],
    resolution: "4K",
    file_type: "mp4",
    video_url: "https://storage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80",
    views_count: 6400,
    saves_count: 1700,
    created_at: "2026-04-06T12:00:00Z",
    published_at: "2026-04-06T12:00:00Z",
    aspect_ratio: "16:9",
    language_code: "ar",
  },
];

export const popularSearches = [
  "فيديوهات سورة الكهف",
  "خلفية طبيعة زرقاء",
  "كروما إسلامية",
  "تلاوة هادئة",
  "تصميم خط عربي",
];

export const categories = ["فيديوهات القرآن", "تصاميم إسلامية", "كروما", "مشاهد طبيعية"];

export const reciters = ["مشاري العفاسي", "عبد الباسط", "السديس", "ماهر المعيقلي"];
